# Generated by Django 4.2 on 2024-07-09 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_industry_organization_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.industry'),
        ),
    ]
