version: '3'

volumes:
  postgres_data_local:
    driver: local

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - .:/app
    env_file: ./compose/local/local.env
    depends_on:
      - redis_server
      - postgres_server

  app:
    <<: *django
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  celeryworker:
    <<: *django
    command: celery -A backend worker -l INFO

  redis_server:
    image: redis:6.0

  postgres_server:
    image: postgres:13
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    env_file: ./compose/local/local.env
